### ISSUE TITLE
xyy.py运行出现初始化阅读有问题

### ISSUE THREAD

**Issue by Sakura-Qy** [wyourname/wool#1]
# xyy.py运行出现初始化阅读有问题
您好，非常感谢您提供的代码！我执行xyy.py的时候会出错，好像是 init_read(self) 这里的url有问题，请问要怎么解决呢
![image](https://github.com/wyourname/wool/assets/71543512/0efdc9a1-882a-4600-a27e-5d4fcc719878)

**Comment by wyourname** [comment]
emmm你可以把ck给我测试一下或者你确定你的ck是否更新了ck变更为3eace20......这种格式了

**Comment by wyourname** [comment]
我刚刚看了下你的ck并没有更新，你需要更新你的ck,重新抓取就行，我用旧ck还原出了

**Comment by wyourname** [comment]
> # xyy.py 运行出现初始化阅读有问题
> 您好，非常感谢您提供的代码！我执行 xyy.py 的时候会出错，好像是 init_read（self） 这里的url有问题，请问要怎么解决呢 ![图像](https://user-images.githubusercontent.com/71543512/273429905-0efdc9a1-882a-4600-a27e-5d4fcc719878.png)

我刚刚看了下你的ck并没有更新，你需要更新你的ck，重新抓取就行，我用旧ck还原出了,如果还是出现该问题请B站联系我 B站用户名:我要有只喵喵喵

**Comment by Sakura-Qy** [comment]
> > # xyy.py 运行出现初始化阅读有问题
> > 您好，非常感谢您提供的代码！我执行 xyy.py 的时候会出错，好像是 init_read（self） 这里的url有问题，请问要怎么解决呢 ![图像](https://user-images.githubusercontent.com/71543512/273429905-0efdc9a1-882a-4600-a27e-5d4fcc719878.png)
> 
> 我刚刚看了下你的ck并没有更新，你需要更新你的ck，重新抓取就行，我用旧ck还原出了,如果还是出现该问题请B站联系我 B站用户名:我要有只喵喵喵

谢谢，我看了您发的公告后，把我的环境变量填写内容修改之后就行了，原来的是填写了所有的cookie，后来只填了字段后面的字符串就运行正常了。现在去关注大佬的b站👍👍👍
