### ISSUE TITLE
57box

### ISSUE THREAD

**Issue by 2000dia** [wyourname/wool#2]
你好我想问一下这个新版本的57box自动抽奖怎么关闭

**Comment by wyourname** [comment]
> 你好我想问一下这个新版本的57box自动抽奖怎么关闭
需要关的话我加开关功能吧

**Comment by 2000dia** [comment]
> > 你好我想问一下这个新版本的57box自动抽奖怎么关闭
> > 需要关的话我加开关功能吧

加一个吧谢谢大佬主要是那个奖池只有一个可乐其他东西感觉不好哈哈哈

**Comment by wyourname** [comment]
> > > 你好我想问一下这个新版本的57box自动抽奖怎么关闭
> > > 需要关的话我加开关功能吧
> 
> 加一个吧谢谢大佬主要是那个奖池只有一个可乐其他东西感觉不好哈哈哈

已经加上了，请拉取脚本运行脚本就行

**Comment by wyourname** [comment]
> > > 你好我想问一下这个新版本的57box自动抽奖怎么关闭
> > > 需要关的话我加开关功能吧
> 
> 加一个吧谢谢大佬主要是那个奖池只有一个可乐其他东西感觉不好哈哈哈

脚本自动关闭开盲盒了需要打开就手机号#密码#1的格式填就行

**Comment by 2000dia** [comment]
> > > > 你好我想问一下这个新版本的57box自动抽奖怎么关闭
> > > > 需要关的话我加开关功能吧
> > 
> > 
> > 加一个吧谢谢大佬主要是那个奖池只有一个可乐其他东西感觉不好哈哈哈
> 
> 脚本自动关闭开盲盒了需要打开就手机号#密码#1的格式填就行
谢谢大佬
