### ISSUE TITLE
中青看点快应用怎么更新后，显示当前环境不允许执行

### ISSUE THREAD

**Issue by wzal2008** [wyourname/wool#5]

**Comment by wyourname** [comment]
同地方的ip同账号数量过多，后台禁用了，http://myip.ipip.net提供你的ip给我解除

**Comment by wzal2008** [comment]
我的ip36.34.85.11,麻烦大佬解除下。

**Comment by wyourname** [comment]
> 我的ip36.34.85.11,麻烦大佬解除下。

请减少你的容器，多余的号请放置在同一个容器之中

**Comment by wzal2008** [comment]
好的，已全部放在一个容器运行，请解封下，我有6~7个号，谢了。

**Comment by wyourname** [comment]
> 好的，已全部放在一个容器运行，请解封下，我有6~7个号，谢了。

明天自动解封的
